# Generated by Django 4.0.1 on 2022-04-09 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewplatform',
            name='tutorial_discription',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addnewplatform',
            name='tutorial_video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='addnewplatform',
            name='uploadthumbnail',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
